#!/bin/sh
# init psprcs
#
# chkconfig: 2345 90 60
# description: start/stop PeopleSoft Process Scheduler services
# this script uses psadmin 
# http://docs.oracle.com/cd/E38689_01/pt853pbr0/eng/pt/tsvt/task_UsingthePSADMINCommand-LineInterface-c07e70.html
# http://peoplesoft.ittoolbox.com/groups/technical-functional/peoplesoft-other-l/auto-startup-script-for-peoplesoft-apps-server-process-schedular-and-pia-554662

# 06/10/2014 ESAI -mmacdo02 (michael.macdonald@tufts.edu):

# Define these variables
#########################
PSDOMAIN=FINDEV
PSUSER=psfm
#########################
RETVAL=0

. /etc/init.d/functions

if [ $UID != 0 ]; then
        echo This script must be run using sudo or as root.
        exit 1
fi

psprcs_start() {
  echo Starting psprcs...
  runuser -l $PSUSER -c "/$PSUSER/fm/appserv/psadmin -p start -d $PSDOMAIN"
  
RETVAL=$?
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/psprcs

}
psprcs_stop() {
  echo Stopping psprcs...
  runuser -l $PSUSER -c "/$PSUSER/fm/appserv/psadmin -p stop -d $PSDOMAIN"

  RETVAL=$?
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/psprcs

}
psprcs_restart() {
  echo Restarting psprcs..
  psprcs_stop
  psprcs_flush
  psprcs_start
  RETVAL=$?
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/psprcs
}

psprcs_flush() {
  echo Flushing psprcs..
  runuser -l $PSUSER -c "/$PSUSER/fm/appserv/psadmin -p cleanipc -d $PSDOMAIN"
}

psprcs_configure() {
  echo Configuring psprcs..
  runuser -l $PSUSER -c "/$PSUSER/fm/appserv/psadmin -p configure -d $PSDOMAIN"
}

psprcs_status() {
  echo psprcs server status:
  runuser -l $PSUSER -c "/$PSUSER/fm/appserv/psadmin -p status -d $PSDOMAIN"
  RETVAL=$?

}
case "$1" in
  start)
    psprcs_start
    ;;
  stop)
    psprcs_stop
    ;;
  restart)
    psprcs_restart
	    ;;
  status)
    psprcs_status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $RETVAL

